/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 *
 * @author Thiago
 */
public class JfrPaint extends javax.swing.JFrame {

    /**
     * Creates new form JfrPaint
     */
    Retangulo ret = new Retangulo(0, 0);
    D1 reta = new D1(0, 0);
    Circulo circ = new Circulo(0, 0);
    Spray spray = new Spray(0, 0);
    D0 p = new D0(0, 0);
    Cilindro ci = new Cilindro(0, 0);
    Borracha bor = new Borracha(0, 0);
    Poligono pol = new Poligono(0, 0);

    enum TipoFigura {
        tfPonto, tfReta, tfCirculo, tfRetangulo, tfBorracha, tfSpray, tfCilindro, tfPoligono
    };
    TipoFigura tipoFigura = TipoFigura.tfPonto;
    int aux1 = 1;
    int aux2 = 1;

    public JfrPaint() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        AbstractColorChooserPanel[] panels = pnlCor.getChooserPanels();
        pnlCor.remove(1);

        for (AbstractColorChooserPanel p : panels) {
            String displayName = p.getDisplayName();

            System.out.println(displayName);
            switch (displayName) {
                case "HSV":
                    pnlCor.removeChooserPanel(p);
                    break;
                case "HSL":
                    pnlCor.removeChooserPanel(p);
                    break;
                case "CMYK":
                    pnlCor.removeChooserPanel(p);
                    break;
                case "RGB":
                    pnlCor.removeChooserPanel(p);
                    break;
                case "Swatch":
                    pnlCor.removeChooserPanel(p);
                    break;

            }
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlPaint = new javax.swing.JPanel();
        btnPonto = new javax.swing.JButton();
        btnReta = new javax.swing.JButton();
        btnRetangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnSpray = new javax.swing.JButton();
        btnCilindro = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        corInt = new javax.swing.JPanel();
        corExt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlCor = new javax.swing.JColorChooser();
        checkbox1 = new javax.swing.JCheckBox();
        checkbox2 = new javax.swing.JCheckBox();
        btnBorracha = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSalvar = new javax.swing.JMenu();
        btnNovo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1600, 900));

        pnlPaint.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaint.setPreferredSize(new java.awt.Dimension(1366, 527));
        pnlPaint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlPaintMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlPaintMouseMoved(evt);
            }
        });
        pnlPaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPaintMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlPaintMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPaintLayout = new javax.swing.GroupLayout(pnlPaint);
        pnlPaint.setLayout(pnlPaintLayout);
        pnlPaintLayout.setHorizontalGroup(
            pnlPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPaintLayout.setVerticalGroup(
            pnlPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );

        btnPonto.setBackground(new java.awt.Color(240, 240, 255));
        btnPonto.setForeground(new java.awt.Color(240, 240, 255));
        btnPonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/lapis.png"))); // NOI18N
        btnPonto.setBorderPainted(false);
        btnPonto.setMaximumSize(new java.awt.Dimension(577, 521));
        btnPonto.setPreferredSize(new java.awt.Dimension(577, 521));
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnReta.setBackground(new java.awt.Color(240, 240, 255));
        btnReta.setForeground(new java.awt.Color(240, 240, 255));
        btnReta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/reta.png"))); // NOI18N
        btnReta.setToolTipText("");
        btnReta.setBorderPainted(false);
        btnReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetaActionPerformed(evt);
            }
        });

        btnRetangulo.setBackground(new java.awt.Color(240, 240, 255));
        btnRetangulo.setForeground(new java.awt.Color(240, 240, 255));
        btnRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/retangulo.png"))); // NOI18N
        btnRetangulo.setBorderPainted(false);
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnCirculo.setBackground(new java.awt.Color(240, 240, 255));
        btnCirculo.setForeground(new java.awt.Color(240, 240, 255));
        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/circulo.png"))); // NOI18N
        btnCirculo.setBorderPainted(false);
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnSpray.setBackground(new java.awt.Color(240, 240, 255));
        btnSpray.setForeground(new java.awt.Color(240, 240, 255));
        btnSpray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/spray.png"))); // NOI18N
        btnSpray.setBorderPainted(false);
        btnSpray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSprayMouseClicked(evt);
            }
        });

        btnCilindro.setBackground(new java.awt.Color(240, 240, 255));
        btnCilindro.setForeground(new java.awt.Color(240, 240, 255));
        btnCilindro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/cilindro.png"))); // NOI18N
        btnCilindro.setBorderPainted(false);
        btnCilindro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCilindroMouseClicked(evt);
            }
        });
        btnCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCilindroActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(240, 240, 255));
        jButton7.setForeground(new java.awt.Color(240, 240, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/poligono.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        corInt.setBackground(new java.awt.Color(0, 0, 0));
        corInt.setPreferredSize(new java.awt.Dimension(60, 20));
        corInt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corIntMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout corIntLayout = new javax.swing.GroupLayout(corInt);
        corInt.setLayout(corIntLayout);
        corIntLayout.setHorizontalGroup(
            corIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        corIntLayout.setVerticalGroup(
            corIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        corExt.setBackground(new java.awt.Color(0, 0, 0));
        corExt.setPreferredSize(new java.awt.Dimension(60, 0));
        corExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corExtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout corExtLayout = new javax.swing.GroupLayout(corExt);
        corExt.setLayout(corExtLayout);
        corExtLayout.setHorizontalGroup(
            corExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        corExtLayout.setVerticalGroup(
            corExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jLabel1.setText("Cor interna");

        jLabel2.setText("Cor externa");

        checkbox1.setText("Área");
        checkbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox1ActionPerformed(evt);
            }
        });

        checkbox2.setText("Perímetro");
        checkbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox2ActionPerformed(evt);
            }
        });

        btnBorracha.setBackground(new java.awt.Color(240, 240, 255));
        btnBorracha.setForeground(new java.awt.Color(240, 240, 255));
        btnBorracha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/Assets/borracha.png"))); // NOI18N
        btnBorracha.setBorderPainted(false);
        btnBorracha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrachaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBorrachaMouseReleased(evt);
            }
        });

        btnSalvar.setText("Arquivo");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalvarMousePressed(evt);
            }
        });

        btnNovo.setText("Novo projeto");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovoMousePressed(evt);
            }
        });
        btnSalvar.add(btnNovo);

        jMenuItem3.setText("Salvar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        btnSalvar.add(jMenuItem3);
        btnSalvar.add(jSeparator1);

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });
        btnSalvar.add(btnSair);

        jMenuBar1.add(btnSalvar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnReta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSpray, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorracha, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(corInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(corExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(pnlCor, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(684, 684, 684))
            .addComponent(pnlPaint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkbox2)
                                    .addComponent(checkbox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(corExt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCilindro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSpray, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnBorracha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(pnlPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfPonto;

    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCilindroActionPerformed
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfCilindro;
    }//GEN-LAST:event_btnCilindroActionPerformed

    private void btnBorrachaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfBorracha;
    }


    private void pnlPaintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaintMousePressed
        // TODO add your handling code here:
        if (tipoFigura == TipoFigura.tfPonto) {
            p.cor = pnlCor.getColor();
            p.x = evt.getX();
            p.y = evt.getY();
            p.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfRetangulo) {
            ret.cor = corExt.getBackground();
            ret.corInterna = corInt.getBackground();
            ret.x = evt.getX();
            ret.y = evt.getY();

        } else if (tipoFigura == TipoFigura.tfReta) {
            reta.x = evt.getX();
            reta.y = evt.getY();
            reta.cor = corExt.getBackground();
        } else if (tipoFigura == TipoFigura.tfCirculo) {
            circ.cor = corExt.getBackground();
            circ.corInterna = corInt.getBackground();
            circ.x = evt.getX();
            circ.y = evt.getY();
        } else if (tipoFigura == TipoFigura.tfSpray) {
            spray.cor = corInt.getBackground();
            spray.x = evt.getX();
            spray.y = evt.getY();
            spray.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfCilindro) {
            ci.cor = corInt.getBackground();
            ci.x = evt.getX();
            ci.y = evt.getY();

        } else if (tipoFigura == TipoFigura.tfBorracha) {
            bor.cor = corExt.getBackground();
            bor.corInterna = corInt.getBackground();
            bor.x = evt.getX();
            bor.y = evt.getY();
            bor.base = 30;
            bor.largura = 30;
            bor.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfPoligono) {
            pol.x = evt.getX();
            pol.y = evt.getY();
            pol.cor = pnlCor.getBackground();
            pol.desenhar(pnlPaint.getGraphics()); //desenha o ponto q vai ser traçado no poligono
        }
         if (tipoFigura == TipoFigura.tfPoligono) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                pol.formarPoligono(pnlPaint.getGraphics());
                pol.limparListaPontos();
            }
        }
       
    }//GEN-LAST:event_pnlPaintMousePressed


    private void pnlPaintMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaintMouseReleased
        // TODO add your handling code here:
        if (tipoFigura == TipoFigura.tfRetangulo) {
            ret.base = evt.getX() - ret.x;
            ret.largura = evt.getY() - ret.y;
            ret.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfReta) {
            reta.x1 = evt.getX();
            reta.y1 = evt.getY();
            reta.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfCirculo) {
            circ.base = evt.getX() - circ.x;
            circ.altura = evt.getY() - circ.y;
            circ.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfCilindro) {
            ci.base = evt.getX() - ci.x;
            ci.altura = evt.getY() - ci.y;
            ci.desenhar(pnlPaint.getGraphics());
        }
    }//GEN-LAST:event_pnlPaintMouseReleased

    private void btnRetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetaActionPerformed
        tipoFigura = TipoFigura.tfReta;
    }//GEN-LAST:event_btnRetaActionPerformed

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        tipoFigura = TipoFigura.tfRetangulo;
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        tipoFigura = TipoFigura.tfCirculo;
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void corIntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corIntMouseClicked
        corInt.setBackground(pnlCor.getColor());
    }//GEN-LAST:event_corIntMouseClicked

    private void corExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corExtMouseClicked
        // TODO add your handling code here:
        corExt.setBackground(pnlCor.getColor());

    }//GEN-LAST:event_corExtMouseClicked

    private void btnSprayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSprayMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfSpray;
    }//GEN-LAST:event_btnSprayMouseClicked

    private void pnlPaintMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaintMouseDragged
        // TODO add your handling code here:
        if (tipoFigura == TipoFigura.tfSpray) {
            spray.x = evt.getX();
            spray.y = evt.getY();
            spray.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfPonto) {
            p.x = evt.getX();
            p.y = evt.getY();
            p.desenhar(pnlPaint.getGraphics());
        } else if (tipoFigura == TipoFigura.tfBorracha) {
            bor.x = evt.getX();
            bor.y = evt.getY();
            bor.base = 30;
            bor.largura = 30;
            bor.desenhar(pnlPaint.getGraphics());

        }
    }//GEN-LAST:event_pnlPaintMouseDragged

    private void pnlPaintMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaintMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlPaintMouseMoved

    private void btnCilindroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCilindroMouseClicked
        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfCilindro;
    }//GEN-LAST:event_btnCilindroMouseClicked

    private void checkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox1ActionPerformed
        // TODO add your handling code here:

        if (aux1 % 2 != 0) {
            circ.showArea = true;
            ret.showArea = true;
            System.out.println("ativou");

        } else if (aux1 % 2 == 0) {
            circ.showArea = false;
            ret.showArea = false;
            System.out.println("desativou");

        }
        aux1++;

    }//GEN-LAST:event_checkbox1ActionPerformed

    private void checkbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox2ActionPerformed
        // TODO add your handling code here:
        if (aux2 % 2 != 0) {
            circ.showPerimetro = true;
            ret.showPerimetro = true;
            System.out.println("ativou");

        } else if (aux2 % 2 == 0) {
            circ.showPerimetro = false;
            ret.showPerimetro = false;
            System.out.println("desativou");

        }

        aux2++;
    }//GEN-LAST:event_checkbox2ActionPerformed

    private void btnBorrachaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrachaMouseReleased
    }//GEN-LAST:event_btnBorrachaMouseReleased

    private void btnBorrachaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrachaMouseClicked
        // TODO add your handling code here:]           tipoFigura = TipoFigura.tfBorracha;        // TODO add your handling code here:
        tipoFigura = TipoFigura.tfBorracha;        // TODO add your handling code here:

    }//GEN-LAST:event_btnBorrachaMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        //  JfrPaint.setDefaultCloseOperation(JfrPaint.EXIT_ON_CLOSE);

    }//GEN-LAST:event_btnSairMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnNovoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMousePressed
        // TODO add your handling code here:

        ret.corInterna = Color.white;
        ret.x = 0;
        ret.y = 0;
        ret.largura = 527;
        ret.base = 1366;
        ret.desenhar(pnlPaint.getGraphics());
    }//GEN-LAST:event_btnNovoMousePressed

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairMousePressed

    private void btnSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMousePressed
        BufferedImage img = new BufferedImage(this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_RGB);
        this.paint(img.getGraphics());
        File outputfile = new File("saved.png");
        try {
            ImageIO.write(img, "png", outputfile);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(JfrPaint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarMousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7MousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                tipoFigura = TipoFigura.tfPoligono;

       
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JfrPaint().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorracha;
    private javax.swing.JButton btnCilindro;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JMenuItem btnNovo;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnReta;
    private javax.swing.JButton btnRetangulo;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenu btnSalvar;
    private javax.swing.JButton btnSpray;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkbox1;
    private javax.swing.JCheckBox checkbox2;
    private javax.swing.JPanel corExt;
    private javax.swing.JPanel corInt;
    private javax.swing.JButton jButton7;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JColorChooser pnlCor;
    private javax.swing.JPanel pnlPaint;
    // End of variables declaration//GEN-END:variables
}
